# Generated by Django 6.0.3 on 2026-03-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_rename_assigned_user_task_assignee_task_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='to-do', max_length=20),
        ),
    ]
