# Generated by Django 6.0.3 on 2026-03-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0004_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
